HOPE/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from HOPE import views

urlpatterns = [
    url(r'^$',views.login_redirect,name="login_redirect"),
    url(r'^admin/', admin.site.urls),
    url(r'^new/', include(('new.urls', 'new'), namespace='new')),
    url(r'^home/', include(('home.urls', 'home'), namespace='home')),
    url(r'^chat/', include('chat.urls')),
]

home/urls.py
from django.conf.urls import url,include
from home.models import Post

from django.views.generic import ListView,DetailView
from . import views

urlpatterns = [
    #url('', views.post_list, name='post_list'),
    url(r'^post$',ListView.as_view(queryset = Post.objects.all().order_by('-created'),template_name="home/post_list.html")),
    url(r'^post/(?P<pk>\d+)$',DetailView.as_view(model = Post ,template_name="home/post_detail.html")),
    url(r'^post/(?P<pk>\d+)$',views.post_detail ,name="post_detail"),
    #url(r'^post/(?P<pk>\d+)/', views.post_detail, name='post_detail'),
    url(r'^post/new', views.post_new, name='post_new'),
    url(r'^post/(?P<pk>\d+)/edit/$', views.post_edit, name='post_edit'),
    url(r'^post/(?P<pk>\d+)/remove/$', views.post_remove, name='post_remove'),
    url(r'^post/(?P<pk>\d+)/comment/$', views.add_comment, name='add_comment'),
    #url(r'^unlike/(?P<pk>\d)', views.unlike, name = 'unlike'),
    #url(r'^post/like/(?P<pk>\d+/$)', views.like, name = 'like'),
    #url(r'^post/unlike/(?P<id>\w{0,50})$', views.unlike, name = 'unlike'),
    url(r'^post/like/(?P<pk>\d+)/', views.like, name = 'like'),
]

new/urls.py
from django.conf.urls import url
from new import views
from django.contrib.auth.views import login,logout

urlpatterns=[
	 url(r'^login/$', login, {'template_name':'new/login1.html'}),
	 url(r'^logout/$', logout, {'template_name':'new/logout.html'}),
	 url(r'^register/$',views.register, name="register"),
	 url(r'^profile/$',views.view_profile, name="view_profile"),
	 url(r'^profile/(?P<pk>\d+)/$',views.view_profile, name="view_profile_with_pk"),
	 url(r'^profile/edit/$',views.edit_profile, name="edit_profile"),
	 url(r'^profile/change_password/$',views.change_password, name="edit_profile")
]

home/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

# Create your models here.
class Post(models.Model):
	title = models.CharField(max_length=500,default="TITLE")
	post = models.TextField(max_length=500,default="POST")
	user =  models.ForeignKey(User,on_delete=models.CASCADE, )
	created = models.DateTimeField(auto_now_add=True)
	likes = models.IntegerField(default = 0)

	def __str__(self):
		return self.title

class Comment(models.Model):
    post = models.ForeignKey('home.Post', on_delete=models.CASCADE, related_name='comments')
    author = models.CharField(max_length=200, default='xxxxx')
    text = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.text

class Addlikes(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField(default='xxxxx')
    liketime = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.post

home/forms.py
from django import forms
from .models import Post, Comment

class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('title', 'post',)

class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('text',)


'''from django import forms
from home.models import post,comment


class HomeForm(forms.ModelForm):
	post = forms.CharField(widget=forms.TextInput(
	attrs={
	'placeholder':'Enter your Blog post'
	}
	))
	type = forms.CharField(widget=forms.TextInput(
	attrs={
	'placeholder':'Enter the Type of Post'
	}
	))

	class Meta:
		model = post
		fields = ('post','type')

class CommentForm(forms.ModelForm):
	comment = forms.CharField(widget=forms.TextInput(
	attrs={
	'placeholder':'Enter your Comment'
	}
	))

	class Meta:
		model = comment
		fields = ('comment',)

'''

home/views.py

from django.shortcuts import render,redirect
from django.http import HttpResponse,HttpResponseRedirect
#from home.forms import HomeForm,CommentForm
#from home.models import post,comment
from django.contrib.auth.models import User
#from django.views.generic import TemplateView
#from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404
from django.utils import timezone
from .models import Post, Comment,Addlikes
from .forms import PostForm, CommentForm


def post_detail(request, pk):
    post = get_object_or_404(Post,pk=request.pk)
    return render(request, 'home/post_detail.html', {'post': post})

def post_new(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.created = timezone.now()
            post.save()
            return redirect('/home/post')
    else:
        form = PostForm()
    return render(request, 'home/add.html', {'form': form})


def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.save()
            return redirect('/home/post')
    else:
        form = PostForm(instance=post)
    return render(request, 'home/post_edit.html', {'form': form})


def post_remove(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.user == post.user:
        post.delete()
    return redirect('/home/post')

def add_comment(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.author = request.user
            comment.save()
            return redirect('/home/post')
    else:
        form = CommentForm()
    return render(request, 'home/comment.html', {'form': form})

def like(request, pk):
    post = get_object_or_404(Post, pk=pk)
    likes = Addlikes.objects.all()
    print (post)
    print (likes.text)
    #print (likes.user_id)
    if request.method == "GET":
        p = Post.objects.get(pk=pk)
        p.likes+=1
        p.save()
        b = Addlikes(post=post, user=request.user)
        b.save()
    return HttpResponseRedirect('/home/post/'+pk)


#def search(request):

home/templates/home/add.html
{% extends 'base.html' %}
{%load crispy_forms_tags%}

{% block body %}
<center>
    <h1>New post</h1>
 <div class="w3-container w3-grey" style="height: 390px; width: 600px";>
    <form method="POST">
    	{% csrf_token %}
        {{ form|crispy }}
        <br>
        <button type="submit" class="save btn btn-success">ADD POST</button>
    </form>
  </div>
</center>
{% endblock %}

home/templates/home/comment.html
{% extends 'base.html' %}
{% block body %}
    <h3>New comment</h3>
    <form method="POST" class="post-form">
    	{% csrf_token %}
        {{ form.text }}
        <button type="submit" class="save btn btn-default">Comment</button>
    </form>
{% endblock %}

home/templates/home/post_detail.html
{% extends 'base.html' %}

{% block body %}
    <div class="post">
        {% if user.is_authenticated %}
        <button class="btn btn-default"><a href="{% url 'home:post_remove' post.id %}">DELETE THIS POST</a></button>
        <button class="btn btn-default"><a href="{% url 'home:post_edit' post.id %}">EDIT THIS POST</a></button>
        {% endif %}
        {% if post.created %}
            <div class="date">
                {{ post.created }}
            </div>
        {% endif %}
        <u><h1>{{ post.title }}</h1></u>
        <h3>{{ post.post }}</h3>
        <u><h2>{{ post.user }}</h2></u>
         <u><h2>LIKES :{{ post.likes }}</h2></u>
        <br><br>
        <button class="btn btn-success"><a href="{% url 'home:like' post.id %}">LIKE</a></button>
    </div>
    <h3>COMMENTS!!</h3>
    <button class="btn btn-default"><a href="{% url 'home:add_comment' post.id %}">ADD COMMENT</a></button>
    {% for comment in post.comments.all %}
        <div class="comment">
            <div class="date">{{ comment.created_date }}</div>
            <strong>{{ comment.author }}</strong>
            <p>{{ comment.text}}</p>
        </div>
        {% empty %}
            <p>No comments</p>
    {% endfor %}
{% endblock %}

home/templates/home/post_edit.html
{% extends 'base.html' %}
{%load crispy_forms_tags%}

{% block body %}
    <h1>EDIT post</h1>
    <form method="POST" class="post-form">
    	{% csrf_token %}
        {{ form|crispy }}
        <br>
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
{% endblock %}

home/templates/home/post_list.html
{% extends 'base.html' %}
{% block body%}

<div class="container">
    {% for post in object_list %}
    <h2><a href="/home/post/{{post.id}}">{{ post.title}}</a></h2>
    <h4>{{post.post}}</h4>
    <u>
    <h4> BY {{post.user}}</h4>
    <h4>POSTED ON {{post.created}}</h4></u>
    {% endfor %}
</div>
{% endblock %}